version: "3.7"

services:
  mysql:
    image: mariadb:10.4
    environment:
      MARIADB_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 3306:3306