version: "3.7"

services:
  mysql:
    image: mariadb:10.4
    environment:
      MARIADB_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - '4856:4856'
    volumes:
      - /home/ubuntu/test/db/data:/var/lib/mysql
  spring-crud-example:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: container_app
    links:
      - mysql
    restart: always
    ports:
      - "80:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:4856/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
