version: "3.7"

services:
  spring-crud-example:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: container_app
    restart: always
    ports:
      - "80:8080"
    tty: true
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://fgfdb.cmimwlzbjnub.ap-northeast-2.rds.amazonaws.com:3306/fgfDB?useSSL=false&autoReconnect=true&character_set_server=utf8mb4
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: qweasd123