spring:
  datasource:
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: jdbc:h2:mem:paging-db
    membername : sa
    driver-class-name: com.mysql.cj.jdbc.Driver

    h2:
      console:
        enabled : true
        path: /h2-console

  jpa:
    show-sql: true
    properties:
    generate-ddl: true
    hibernate:
      format_sql: true
      ddl-auto: create-drop

      javax:
        sharedcache:
          mode: ENABLE_SELECTIVE

      generate_ddl: true
      hibernate:
        ddl-auto: create
server:
  port: 8080