spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    hibernate:
      ddl-auto: create
  jackson:
    property-naming-strategy: SNAKE_CASE
server:
  port: 8080