name: Test-Lint-Build
on:
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run java checkstyle
        uses: nikitasavinov/checkstyle-action@0.5.1

      - name: Set Gradle As Excutable
        run: chmod +x gradlew

      - name: Run Test With Gradle
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build



